version: '3.3'
services:

  php:
    build:
      context: ./php
    container_name: php
    volumes:
    - "../:/var/www/project"

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - "../:/var/www/project"
    - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    container_name: adminer
    ports:
    - 8080:8080